---
- name: Find AWS credentials and tower instance list files
  find:
    paths: ./inventories/group_vars/all
    patterns: "*_list.yml"
  register: files_to_delete

- name: Deleting list files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  register: files