---
- name: Encrypting variables
  block:
  - name: "Encrypting variable: {{ item.name }}"  
    copy:
      content: "{{ item.value }}"
      dest: /tmp/{{ item.name }}.yml
  - shell: ansible-vault encrypt /tmp/{{ item.name }}.yml --vault-password-file '/tmp/vault_password.yml' && sed -i -e 's/^/  /' /tmp/{{ item.name }}.yml
  - set_fact:
      "{{ item.name }}_enc": "{{ lookup('file', '/tmp/{{ item.name }}.yml') }}"
  - file:
      state: absent
      path: "/tmp/{{ item.name }}.yml"