---
- name: Creating the vault password file
  copy:
      content: "{{ vault_password }}"
      dest: /tmp/vault_password.yml

- name: Reset provisioning_vars template
  copy:
    src: roles/credentials/files/provisioning_vars.yml.j2
    dest: files/provisioning_vars.yml.j2

- name: Encrypt provisioning_vars.yml.j2
  shell: ansible-vault encrypt files/provisioning_vars.yml.j2 --vault-password-file /tmp/vault_password.yml
  

  